### PR TITLE
LPS-57261 make sure that we don't clobber shared sessions

### PR DESCRIPTION
**Pull request by rotty3000**
Can you confirm my change works like you expect?

### CODE REVIEW

**Comment by mjbradford89** [comment]
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

**Comment by mjbradford89** [comment]
Hey @rotty3000, This looks good, works as I would expect. should I forward to Brian?

**Comment by rotty3000** [comment]
Sure

- Ray (mobile)

**Comment by mjbradford89** [comment]
forwarded to brian: https://github.com/brianchandotcom/liferay-portal/pull/28780

**Pull request closed without merging**
