### PR TITLE
LPS-57267 - TypeError: portletItem.delegate is undefined upon clicking the plus icon for the first time in Firefox

### PR DESCRIPTION
**Pull request by mjbradford89**

### CODE REVIEW

**Comment by mjbradford89** [comment]
ci:retest

**Comment by mjbradford89** [comment]
ci:retest

**Comment by mjbradford89** [comment]
ci:retest

**Comment by mjbradford89** [comment]
ci:retest

**Comment by brianchiu** [comment]
Nice! portal smoke test passed on this.

**Comment by brianchiu** [comment]
ci:retest

**Pull request closed without merging**
